# Generated by Django 5.2.4 on 2025-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cmPassword',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
