# Generated by Django 5.2.4 on 2025-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_register_cmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
