# Generated by Django 5.2.4 on 2025-07-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_register_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cmPassword',
        ),
    ]
