# Generated by Django 5.2.4 on 2025-07-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_register_cmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='otp',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
