# Generated by Django 5.2.4 on 2025-07-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_category_id_product_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.category'),
        ),
    ]
