# Generated by Django 5.2.4 on 2025-07-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_product_descriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Main_Category',
        ),
    ]
