# Generated by Django 5.2.4 on 2025-07-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_rename_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
