# Generated by Django 5.0.6 on 2025-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
