# Generated by Django 5.2.4 on 2025-08-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_brand_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='color',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='color',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='color',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.color'),
        ),
    ]
