# Generated by Django 5.2.4 on 2025-08-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_remove_brand_product_remove_brand_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='color',
            name='main_category',
        ),
    ]
