# Generated by Django 5.2.4 on 2025-08-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_contect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contect',
            name='subject',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
