# Generated by Django 5.2.4 on 2025-08-25 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('price', models.IntegerField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=50, null=True)),
                ('total_price', models.IntegerField(blank=True, max_length=30, null=True)),
                ('prudect_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.product')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.register')),
            ],
        ),
    ]
