# Generated by Django 5.2.4 on 2025-08-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_add_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
