# Generated by Django 5.2.4 on 2025-08-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_alter_add_cart_price_alter_add_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_cart',
            old_name='prudect_id',
            new_name='product_id',
        ),
    ]
