# Generated by Django 5.2.4 on 2025-08-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_rename_prudect_id_add_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='Sub_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
