# Generated by Django 5.2.4 on 2025-08-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_add_cart_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='Sub_total',
        ),
    ]
