# Generated by Django 5.2.4 on 2025-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_remove_add_cart_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
