# Generated by Django 5.2.4 on 2025-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_add_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='total_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
