# Generated by Django 5.2.4 on 2025-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_add_cart_total_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('discount', models.IntegerField(blank=True, default=100, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
