# Generated by Django 5.2.4 on 2025-08-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_rename_discount_coupon_discount2_alter_coupon_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cart',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.coupon'),
        ),
    ]
