# Generated by Django 5.2.4 on 2025-08-31 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_alter_add_cart_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='register',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.coupon'),
        ),
    ]
