# Generated by Django 5.2.4 on 2025-08-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_remove_add_cart_coupon_code_register_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='coupon_code',
        ),
    ]
