# Generated by Django 5.2.4 on 2025-09-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_remove_register_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='add_cart',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
