# Generated by Django 5.2.4 on 2025-09-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.register'),
        ),
    ]
