# Generated by Django 5.2.4 on 2025-09-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_coupon_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user_id',
        ),
        migrations.AddField(
            model_name='add_cart',
            name='coupon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.coupon'),
        ),
    ]
