# Generated by Django 5.2.4 on 2025-09-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_remove_coupon_user_id_add_cart_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='coupon_id',
        ),
    ]
