# Generated by Django 5.2.4 on 2025-09-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0042_remove_coupon_active_coupon_expiry_time_user_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount2',
            new_name='discount',
        ),
    ]
