# Generated by Django 5.2.4 on 2025-09-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_rename_code_coupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_coupon',
            name='coupon_id',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.coupon'),
        ),
        migrations.AlterField(
            model_name='user_coupon',
            name='user_id',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.register'),
        ),
    ]
