# Generated by Django 5.2.4 on 2025-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0046_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
