# Generated by Django 5.2.4 on 2025-09-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0047_alter_checkout_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
