# Generated by Django 5.2.4 on 2025-09-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0049_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.register'),
        ),
    ]
