# Generated by Django 5.2.4 on 2025-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0050_checkout_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
