# Generated by Django 5.2.4 on 2025-09-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0051_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='add_date',
        ),
    ]
