# Generated by Django 5.2.4 on 2025-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0052_remove_order_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
