# Generated by Django 5.2.4 on 2025-09-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0053_order_address1_order_country_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size_order',
        ),
    ]
