# Generated by Django 5.2.4 on 2025-09-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0054_remove_order_description_remove_order_size_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
