# Generated by Django 5.2.4 on 2025-09-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0057_order_address1_order_country_order_img_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
