# Generated by Django 5.2.4 on 2025-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0058_remove_order_address1_remove_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
