# Generated by Django 5.2.4 on 2025-09-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0059_checkout_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_id',
        ),
    ]
