# Generated by Django 5.2.4 on 2025-09-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0060_remove_checkout_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
